# Vermont Signal V2 - FastAPI Backend
app = "vermont-signal-v2-api"
primary_region = "ewr"

[build]
  dockerfile = "Dockerfile.api"

[env]
  PORT = "8000"
  # API keys loaded from secrets

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

  [[http_service.checks]]
    grace_period = "30s"
    interval = "15s"
    method = "GET"
    timeout = "10s"
    path = "/api/health"

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
