# Railway Configuration for Vermont Signal V2
# Multi-service deployment with API and Worker

[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.api"

[deploy]
startCommand = "uvicorn api_server:app --host 0.0.0.0 --port 8000"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
