# Vermont Signal - API Service Configuration
# This file configures the FastAPI backend service

[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.api"

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
