# Railway Configuration for Worker Service
# API service should override this in dashboard settings

[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.worker"

[deploy]
restartPolicyType = "on_failure"
