services:
  # API Service
  - type: web
    name: vermont-signal-api
    env: docker
    dockerfilePath: ./Dockerfile.api
    region: oregon
    plan: starter
    healthCheckPath: /api/health
    envVars:
      - key: PORT
        value: 8000
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: vermont-signal-db
          property: connectionString

databases:
  # PostgreSQL Database
  - name: vermont-signal-db
    databaseName: vermont_signal
    user: vermont_signal
    plan: starter
    region: oregon
